CREATE TABLE ROLES (
  ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(40) NOT NULL,
  DESCRIPCION TEXT
);

CREATE TABLE USUARIOS (
  ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
  LOGIN VARCHAR(10) NOT NULL,
  NOMBRE VARCHAR(40) NOT NULL,
  CLAVE CHAR(64) NOT NULL,
  ROL INT NOT NULL,
  EMAIL VARCHAR(40),
  CONSTRAINT FK_USUARIOS_ROL FOREIGN KEY (ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE UBICACIONES (
  ID_UBICACION INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION TEXT
);

CREATE TABLE TIPOSDISPOSITIVO (
  ID_TIPO_DISPOSITIVO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_TIPO VARCHAR(100) UNIQUE NOT NULL,
  DESCRIPCION TEXT
);
