CREATE TABLE ROLES (
  ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(40) NOT NULL,
  DESCRIPCION TEXT
);

CREATE TABLE USUARIOS (
  ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
  LOGIN VARCHAR(10) NOT NULL,
  NOMBRE VARCHAR(40) NOT NULL,
  CLAVE CHAR(64) NOT NULL,
  ROL INT NOT NULL,
  EMAIL VARCHAR(40),
  CONSTRAINT FK_USUARIOS_ROL FOREIGN KEY (ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE UBICACIONES (
  ID_UBICACION INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION TEXT
);

CREATE TABLE TIPOSDISPOSITIVO (
  ID_TIPO_DISPOSITIVO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_TIPO VARCHAR(100) UNIQUE NOT NULL,
  DESCRIPCION TEXT
);

CREATE TABLE DISPOSITIVOS (
  ID_DISPOSITIVO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_DISPOSITIVO VARCHAR(100) NOT NULL,
  ESTADO_ACTUAL VARCHAR(50) NOT NULL,
  ID_TIPO_DISPOSITIVO INT NOT NULL,
  ID_USUARIO INT NOT NULL,
  ID_UBICACION INT NOT NULL,
  CONSTRAINT FK_DISPOSITIVOS_TIPO FOREIGN KEY (ID_TIPO_DISPOSITIVO) REFERENCES TIPOSDISPOSITIVO(ID_TIPO_DISPOSITIVO),
  CONSTRAINT FK_DISPOSITIVOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT FK_DISPOSITIVOS_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACIONES(ID_UBICACION)
);