INSERT INTO ROLES (NOMBRE, DESCRIPCION) VALUES
('Administrador', 'Rol con todos los permisos'),
('Usuario', 'Rol con permisos limitados');

SELECT * FROM ROLES;
SELECT NOMBRE, DESCRIPCION FROM ROLES ORDER BY NOMBRE ASC;
SELECT * FROM ROLES WHERE NOMBRE = 'Administrador';

INSERT INTO USUARIOS (LOGIN, NOMBRE, CLAVE, ROL, EMAIL) VALUES


SELECT * FROM USUARIOS;
SELECT LOGIN, NOMBRE, EMAIL FROM USUARIOS ORDER BY NOMBRE ASC;
SELECT NOMBRE, LOGIN, ROL FROM USUARIOS WHERE ROL = 2;

INSERT INTO UBICACIONES (NOMBRE, DESCRIPCION) VALUES
('Cocina', 'Ubicación de la cocina A'),
('Sala de living', 'Sala del living'),
('Dormitorio Central', 'Ubicación del dormitorio principal');

SELECT * FROM UBICACIONES;
SELECT NOMBRE, DESCRIPCION FROM UBICACIONES;
SELECT * FROM UBICACIONES WHERE NOMBRE LIKE '%Sala%';

INSERT INTO TIPOSDISPOSITIVO (NOMBRE_TIPO, DESCRIPCION) VALUES
('Luz', 'Luces de la casa'),
('Camara', 'Camaras de seguridad');

SELECT * FROM TIPOSDISPOSITIVO;
SELECT NOMBRE_TIPO, DESCRIPCION FROM TIPOSDISPOSITIVO ORDER BY NOMBRE_TIPO ASC;
SELECT * FROM TIPOSDISPOSITIVO WHERE NOMBRE_TIPO LIKE '%Luz%';


INSERT INTO DISPOSITIVOS (NOMBRE_DISPOSITIVO, ESTADO_ACTUAL, ID_TIPO_DISPOSITIVO, ID_USUARIO, ID_UBICACION) VALUES
('Luz cocina', 'Encendido', 1, 1, 1),
('Camara entrada', 'Apagado', 2, 1, 2),
('Aire living', 'Encendido', 4, 2, 2);

SELECT * FROM DISPOSITIVOS;
SELECT NOMBRE_DISPOSITIVO, ESTADO_ACTUAL FROM DISPOSITIVOS WHERE ESTADO_ACTUAL = 'Encendido';
SELECT NOMBRE_DISPOSITIVO, ID_UBICACION FROM DISPOSITIVOS ORDER BY ID_UBICACION ASC;



INSERT INTO ESCENARIOS (NOMBRE_ESCENARIO, DESCRIPCION, ID_USUARIO) VALUES
('Modo Noche', 'Apagar luces y encender alarma', 1),
('Modo Día', 'Encender luces y apagar alarma', 2);

SELECT * FROM ESCENARIOS;
SELECT NOMBRE_ESCENARIO, DESCRIPCION FROM ESCENARIOS;
SELECT * FROM ESCENARIOS WHERE ID_USUARIO = 1;

INSERT INTO ESCENARIOACCIONESDISPOSITVOS (ACCION_DETALLE, ID_ESCENARIO, ID_DISPOSITIVO) VALUES
('Apagar luz de cocina', 1, 1),
('Encender cámara entrada', 1, 2),
('Encender luz de cocina', 2, 1),
('Apagar cámara entrada', 2, 2);

SELECT * FROM ESCENARIOACCIONESDISPOSITVOS;
SELECT ACCION_DETALLE, ID_DISPOSITIVO FROM ESCENARIOACCIONESDISPOSITVOS;
SELECT * FROM ESCENARIOACCIONESDISPOSITVOS WHERE ID_ESCENARIO = 1;

