CREATE DATABASE smart_home;
USE smart_home;


CREATE TABLE ROLES (
  ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(40) NOT NULL,
  DESCRIPCION TEXT
);


CREATE TABLE USUARIOS (
  ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
  LOGIN VARCHAR(20) NOT NULL,
  NOMBRE VARCHAR(50) NOT NULL,
  CLAVE CHAR(64) NOT NULL,
  ROL INT NOT NULL,
  EMAIL VARCHAR(60),
  CONSTRAINT FK_USUARIOS_ROL FOREIGN KEY (ROL) REFERENCES ROLES(ID_ROL)
);


CREATE TABLE UBICACIONES (
  ID_UBICACION INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION TEXT
);


CREATE TABLE TIPOSDISPOSITIVO (
  ID_TIPO_DISPOSITIVO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_TIPO VARCHAR(100) NOT NULL UNIQUE,
  DESCRIPCION TEXT
);


CREATE TABLE ESCENARIOACCIONESDISPOSITVOS (
  ID_ACCION INT AUTO_INCREMENT PRIMARY KEY,
  ACCION_DETALLE VARCHAR(20) NOT NULL
);



CREATE TABLE ESCENARIOS (
  ID_ESCENARIO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_ESCENARIO VARCHAR(100) NOT NULL,
  ID_TIPO_DISPOSITIVO INT NOT NULL,
  ID_UBICACION INT NOT NULL,
  ID_ACCION INT NOT NULL,
  CONSTRAINT FK_ESCENARIOS_TIPO FOREIGN KEY (ID_TIPO_DISPOSITIVO) REFERENCES TIPOSDISPOSITIVO(ID_TIPO_DISPOSITIVO),
  CONSTRAINT FK_ESCENARIOS_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACIONES(ID_UBICACION),
  CONSTRAINT FK_ESCENARIOS_ACCION FOREIGN KEY (ID_ACCION) REFERENCES ESCENARIOACCIONESDISPOSITVOS(ID_ACCION)
);

CREATE TABLE DISPOSITIVOS (
  ID_DISPOSITIVO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE_DISPOSITIVO VARCHAR(100) NOT NULL,
  ID_ACCION INT NOT NULL,
  ID_TIPO_DISPOSITIVO INT NOT NULL,
  ID_USUARIO INT NOT NULL,
  ID_UBICACION INT NOT NULL,
  CONSTRAINT FK_DISPOSITIVO_ACCION FOREIGN KEY (ID_ACCION) REFERENCES ESCENARIOACCIONESDISPOSITVOS(ID_ACCION),
  CONSTRAINT FK_DISPOSITIVO_TIPO FOREIGN KEY (ID_TIPO_DISPOSITIVO) REFERENCES TIPOSDISPOSITIVO(ID_TIPO_DISPOSITIVO),
  CONSTRAINT FK_DISPOSITIVO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT FK_DISPOSITIVO_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACIONES(ID_UBICACION)
);
